server:
  port: 8102

spring:
  application:
    name: cloud-provider-order-alibaba
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
feign:
  sentinel:
    enabled: true

service-url:
  nacos-user-service: http://cloud-provider-payment-alibaba