server:
  port: 8100

spring:
  application:
    name: cloud-provider-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}